spring.application.name=smartsupply

spring.datasource.url=jdbc:postgresql://localhost:5480/SmartSupply
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# Keycloak Configuration (avec variables d'environnement pour Docker)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/logistics-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/logistics-realm/protocol/openid-connect/certs}

# Actuator pour health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


logging.level.org.smartsupply.SmartSupply.aspect=DEBUG
logging.level.org.smartsupply.SmartSupply=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


server.port=8081
server.servlet.context-path=/